# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [2]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [3]:
# Create a 1-dimensional NumPy array using np.array()


# Create a 2-dimensional NumPy array using np.array()


# Create a 3-dimensional Numpy array using np.array()
array1 = np.array([5,34,90])

array2 = np.array([[6,8,90],
                   [67,2,8],
                   [8,2,5]])

array3 = np.array([[[6,8,90],
                    [67,2,8],
                    [8,2,5],
                    [1,6,0]],
                    [[1,2,3],
                    [4,5,6],
                    [7,8,9],
                    [8,2,5]]])

array1, array2, array3


(array([ 5, 34, 90]),
 array([[ 6,  8, 90],
        [67,  2,  8],
        [ 8,  2,  5]]),
 array([[[ 6,  8, 90],
         [67,  2,  8],
         [ 8,  2,  5],
         [ 1,  6,  0]],
 
        [[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [ 8,  2,  5]]]))

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [4]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
array1.shape


(3,)

In [5]:
array1.ndim

1

In [6]:
array1.dtype

dtype('int64')

In [7]:
array1.size

3

In [8]:
type(array1)

numpy.ndarray

In [9]:
# Attributes of 2-dimensional array


In [10]:
array2.shape

(3, 3)

In [11]:
array2.size

9

In [12]:
# Attributes of 3-dimensional array


In [13]:
array3.shape

(2, 4, 3)

In [14]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
array2_dataframe = pd.DataFrame(array2,
                                index=("a","b", "c"),
                                columns=("c","d","e"))
array2_dataframe

c  d   e
a   6  8  90
b  67  2   8
c   8  2   5

In [15]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [16]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [17]:
# Create an array within a range of 0 and 100 with step 3
range_array = np.arange(0,100,3)
range_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [18]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array1 = np.random.randint(0,10,size=(7,2))
random_array1


array([[3, 4],
       [3, 6],
       [5, 5],
       [5, 4],
       [3, 6],
       [4, 4],
       [7, 1]])

In [19]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_array2 = np.random.random((3,5))
random_array2

array([[0.42850657, 0.78419267, 0.47112466, 0.37179048, 0.67542757],
       [0.97575584, 0.79986703, 0.00512453, 0.21755589, 0.90458785],
       [0.05333817, 0.5604389 , 0.75900757, 0.49325136, 0.47591478]])

In [20]:
# Set the random seed to 42

np.random.seed(42)
# Create a random array of numbers between 0 & 10 of size (4, 6)
random_array3 = np.random.randint(0,10, size=(4,6))
random_array3

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [59]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable

random_array4 = np.random.randint(1,10,size=(3,7))
random_array4
# Find the unique numbers in the array you just created
np.unique(random_array4)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
# Find the 0'th index of the latest array you created
random_array4[0]

array([7, 8, 3, 1, 4, 2, 8])

In [61]:
# Get the first 2 rows of latest array you created
random_array4[:2,:]

array([[7, 8, 3, 1, 4, 2, 8],
       [4, 2, 6, 6, 4, 6, 2]])

In [62]:
# Get the first 2 values of the first 2 rows of the latest array
random_array4[:2,:2]

array([[7, 8],
       [4, 2]])

In [64]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_array5 = np.random.randint(0,10,size=(3,5))
ones_2 = np.ones((3,5))

In [66]:
random_array5

array([[0, 7, 2, 2, 0],
       [4, 9, 6, 9, 8],
       [6, 8, 7, 1, 0]])

In [67]:
ones_2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [68]:
# Add the two arrays together
random_array5 + ones_2

array([[ 1.,  8.,  3.,  3.,  1.],
       [ 5., 10.,  7., 10.,  9.],
       [ 7.,  9.,  8.,  2.,  1.]])

In [70]:
# Create another array of ones of shape (5, 3)
ones_3 = np.ones((5,3))
ones_3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [71]:
# Try add the array of ones and the other most recent array together
# random_array5 + ones_3
#broadcasting error


ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [72]:
# Create another array of ones of shape (3, 5)
ones_2


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [73]:
# Subtract the new array of ones from the other most recent array
random_array5 - ones_2

array([[-1.,  6.,  1.,  1., -1.],
       [ 3.,  8.,  5.,  8.,  7.],
       [ 5.,  7.,  6.,  0., -1.]])

In [75]:
# Multiply the ones array with the latest array
random_array5 * ones_2

array([[0., 7., 2., 2., 0.],
       [4., 9., 6., 9., 8.],
       [6., 8., 7., 1., 0.]])

In [76]:
# Take the latest array to the power of 2 using '**'
random_array5 ** 2


array([[ 0, 49,  4,  4,  0],
       [16, 81, 36, 81, 64],
       [36, 64, 49,  1,  0]])

In [77]:
# Do the same thing with np.square()
np.square(random_array5)

array([[ 0, 49,  4,  4,  0],
       [16, 81, 36, 81, 64],
       [36, 64, 49,  1,  0]])

In [78]:
# Find the mean of the latest array using np.mean()
np.mean(random_array5)

4.6

In [80]:
# Find the maximum of the latest array using np.max()
np.max(random_array5)


9

In [81]:
# Find the minimum of the latest array using np.min()
np.min(random_array5)

0

In [83]:
# Find the standard deviation of the latest array
np.std(random_array5)

3.3426536364591137

In [85]:
# Find the variance of the latest array
np.var(random_array5)

11.173333333333336

In [87]:
# Reshape the latest array to (3, 5, 1)
random_array5_reshape = random_array5.reshape((3,5,1))
random_array5_reshape

array([[[0],
        [7],
        [2],
        [2],
        [0]],

       [[4],
        [9],
        [6],
        [9],
        [8]],

       [[6],
        [8],
        [7],
        [1],
        [0]]])

In [88]:
# Transpose the latest array
random_array5.T

array([[0, 4, 6],
       [7, 9, 8],
       [2, 6, 7],
       [2, 9, 1],
       [0, 8, 0]])

What does the transpose do?

In [89]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
random_integers1 = np.random.randint(0,10,size=(3,3))
random_integers2 = np.random.randint(0,10,size=(3,2))


In [90]:
random_integers1

array([[6, 6, 7],
       [4, 2, 7],
       [5, 2, 0]])

In [92]:
random_integers2

array([[2, 4],
       [2, 0],
       [4, 9]])

In [93]:
# Perform a dot product on the two newest arrays you created
np.dot(random_integers1, random_integers2)

array([[52, 87],
       [40, 79],
       [14, 20]])

In [94]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
random_array6 = np.random.randint(0,10,size=(4,3))
random_array7 = np.random.randint(0,10,size=(4,3))

In [95]:
random_array6

array([[6, 6, 8],
       [9, 9, 2],
       [6, 0, 3],
       [3, 4, 6]])

In [97]:
random_array7

array([[6, 3, 6],
       [2, 5, 1],
       [9, 8, 4],
       [5, 3, 9]])

In [98]:
# Perform a dot product on the two newest arrays you created
np.dot(random_array6, random_array7.T)

array([[102,  50, 134, 120],
       [ 93,  65, 161,  90],
       [ 54,  15,  66,  57],
       [ 66,  32,  83,  81]])

It doesn't work. How would you fix it?

In [45]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both


Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [46]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables


In [99]:
# Compare the two arrays with '>'
random_array6 > random_array7

array([[False,  True,  True],
       [ True,  True,  True],
       [False, False, False],
       [False,  True, False]])

What happens when you compare the arrays with `>`?

In [100]:
# Compare the two arrays with '>='
random_array6 >= random_array7

array([[ True,  True,  True],
       [ True,  True,  True],
       [False, False, False],
       [False,  True, False]])

In [103]:
# Find which elements of the first array are greater than 7
random_array6 > 7

array([[False, False,  True],
       [ True,  True, False],
       [False, False, False],
       [False, False, False]])

In [102]:
# Which parts of each array are equal? (try using '==')
random_array6 == random_array7

array([[ True, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [104]:
# Sort one of the arrays you just created in ascending order
np.sort(random_array6)

array([[6, 6, 8],
       [2, 9, 9],
       [0, 3, 6],
       [3, 4, 6]])

In [105]:
# Sort the indexes of one of the arrays you just created
np.argsort(random_array6)

array([[0, 1, 2],
       [2, 0, 1],
       [1, 2, 0],
       [0, 1, 2]])

In [109]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(random_array6)

3

In [110]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(random_array6)

7

In [111]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(random_array6,axis=1)

array([2, 0, 0, 2])

In [112]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(random_array6,axis=0)

array([3, 2, 1])

In [115]:
# Create an array of normally distributed random numbers
normal = np.random.normal(size=(3,3))
normal

array([[-0.2581848 ,  0.46095562, -1.34938997],
       [-1.01907279,  0.12701224, -1.24944372],
       [ 1.94511561, -0.15333646, -0.90698723]])

In [119]:
# Create an array with 10 evenly spaced numbers between 1 and 100
# evenly_spaced = np.random.randint(0,100,10)
# evenly_spaced (does not work lol)
evenly_spaced = np.linspace(1,100,10)
evenly_spaced

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.